name: Apricot Forest Hellas
favicon: null
layout_spectrum: 0.8022727782372385
typography_spectrum: 0.8042226599063724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#bbe6ff'
    - '#636363'
    - '#99989b'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
